my_domain.my_service.helloWorld=NORMAL
my_domain.my_service.criarAgendamento=NORMAL
my_domain.my_service.confirmarAgendamento=NORMAL
my_domain.my_service.cancelarAgendamento=NORMAL
my_domain.my_service.marcarNaoCompareceuPorPeriodo=NORMAL
my_domain.my_service.validarDoacaoPorToken=NORMAL
my_domain.my_service.ajustarEstoque=NORMAL
my_domain.my_service.listarAgendamentosPorPeriodo=NORMAL
my_domain.my_service.listarPontosMapa=NORMAL
my_domain.my_service.buscarUsuarioCloud=NORMAL
my_domain.my_service.buscarDashboardResumoAgendamentos=NORMAL
my_domain.my_service.buscarDashboardSerieAgendamentosPorDia=NORMAL
my_domain.my_service.listarEstoquePorHemocentro=NORMAL
my_domain.my_service.listarTiposEmFalta=NORMAL
my_domain.my_service.doacaoConfirmada=LOW
my_domain.my_service.agendamentoCriado=LOW
my_domain.my_service.agendamentoCancelado=LOW
my_domain.my_service.serviceStarted=LOW
my_domain.my_service.notifyUserEvent=LOW
my_domain.my_service.getMetadata=NORMAL
my_domain.my_service.odata=NORMAL
my_domain.my_service.importUsuario=NORMAL
my_domain.my_service.exportUsuario=NORMAL
my_domain.my_service.importUsuarioEvent=LOW
my_domain.my_service.exportUsuarioEvent=LOW
my_domain.my_service.importHemocentro=NORMAL
my_domain.my_service.exportHemocentro=NORMAL
my_domain.my_service.importHemocentroEvent=LOW
my_domain.my_service.exportHemocentroEvent=LOW
my_domain.my_service.importAgendamentoEvent=LOW
my_domain.my_service.exportAgendamentoEvent=LOW
my_domain.my_service.importDoacaoEvent=LOW
my_domain.my_service.exportDoacaoEvent=LOW
my_domain.my_service.importEstoque=NORMAL
my_domain.my_service.exportEstoque=NORMAL
my_domain.my_service.importEstoqueEvent=LOW
my_domain.my_service.exportEstoqueEvent=LOW
my_domain.my_service.getDependencies=NORMAL
my_domain.my_service.createUsuario=NORMAL
my_domain.my_service.createBulkUsuario=NORMAL
my_domain.my_service.createMergeUsuario=NORMAL
my_domain.my_service.retrieveUsuario=NORMAL
my_domain.my_service.listUsuario=NORMAL
my_domain.my_service.updateUsuario=NORMAL
my_domain.my_service.updateMergeUsuario=NORMAL
my_domain.my_service.deleteUsuario=NORMAL
my_domain.my_service.createUsuario_Agendamentos=NORMAL
my_domain.my_service.createMergeUsuario_Agendamentos=NORMAL
my_domain.my_service.updateUsuario_Agendamentos=NORMAL
my_domain.my_service.updateMergeUsuario_Agendamentos=NORMAL
my_domain.my_service.retrieveUsuario_Agendamentos=NORMAL
my_domain.my_service.deleteUsuario_Agendamentos=NORMAL
my_domain.my_service.listUsuario_Agendamentos=NORMAL
my_domain.my_service.createHemocentro=NORMAL
my_domain.my_service.createBulkHemocentro=NORMAL
my_domain.my_service.createMergeHemocentro=NORMAL
my_domain.my_service.retrieveHemocentro=NORMAL
my_domain.my_service.listHemocentro=NORMAL
my_domain.my_service.updateHemocentro=NORMAL
my_domain.my_service.updateMergeHemocentro=NORMAL
my_domain.my_service.deleteHemocentro=NORMAL
my_domain.my_service.createAgendamento=NORMAL
my_domain.my_service.createBulkAgendamento=NORMAL
my_domain.my_service.createMergeAgendamento=NORMAL
my_domain.my_service.retrieveAgendamento=NORMAL
my_domain.my_service.listAgendamento=NORMAL
my_domain.my_service.updateAgendamento=NORMAL
my_domain.my_service.updateMergeAgendamento=NORMAL
my_domain.my_service.deleteAgendamento=NORMAL
my_domain.my_service.createAgendamento_Doacoes=NORMAL
my_domain.my_service.createMergeAgendamento_Doacoes=NORMAL
my_domain.my_service.updateAgendamento_Doacoes=NORMAL
my_domain.my_service.updateMergeAgendamento_Doacoes=NORMAL
my_domain.my_service.retrieveAgendamento_Doacoes=NORMAL
my_domain.my_service.deleteAgendamento_Doacoes=NORMAL
my_domain.my_service.listAgendamento_Doacoes=NORMAL
my_domain.my_service.createDoacao=NORMAL
my_domain.my_service.createBulkDoacao=NORMAL
my_domain.my_service.createMergeDoacao=NORMAL
my_domain.my_service.retrieveDoacao=NORMAL
my_domain.my_service.listDoacao=NORMAL
my_domain.my_service.updateDoacao=NORMAL
my_domain.my_service.updateMergeDoacao=NORMAL
my_domain.my_service.deleteDoacao=NORMAL
my_domain.my_service.createEstoque=NORMAL
my_domain.my_service.createBulkEstoque=NORMAL
my_domain.my_service.createMergeEstoque=NORMAL
my_domain.my_service.retrieveEstoque=NORMAL
my_domain.my_service.listEstoque=NORMAL
my_domain.my_service.updateEstoque=NORMAL
my_domain.my_service.updateMergeEstoque=NORMAL
my_domain.my_service.deleteEstoque=NORMAL
